-- DESCRIÇÃO DAS TABELAS

DESCRIBE EMPLOYEES

DESC EMPLOYEES

DESC departments

DESC JOBS

DESC locations

-- SELECIONANDO TODOS ELEMENTOS DE UMA TABELA

SELECT *
FROM employees

SELECT *
FROM DEPARTMENTS

SELECT *
FROM JOBS

SELECT *
FROM LOCATIONS

-- SELECIONANDO COLUNAS ESPECIFICAS

SELECT DEPARTMENT_ID, LOCATION_ID
FROM DEPARTMENT

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES

SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID
FROM LOCATIONS

-- ARRASTANDO A TABELA 

SELECT
    job_id,
    job_title
FROM
    jobs;
    
-- EXPRESSÕES ARITIMETRICAS

SELECT FIRST_NAME, LAST_NAME, SALARY, SALARY * 1.15
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY, SALARY + 100 * 1.15
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY, (SALARY + 100) * 1.15
FROM EMPLOYEES;

-- ENTENDENDO O VALOR NULO (NULL) = AUSENCIA DE VALOR

SELECT FIRST_NAME, LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT
FROM EMPLOYEES;

-- UTILIZANDO ALIAS DE COLUNA

SELECT FIRST_NAME AS NOME, LAST_NAME SOBRENOME, SALARY "Salario", COMMISSION_PCT "Percentual de comissão"
FROM EMPLOYEES;
    

-- OPERADOR DE CONCATENAÇÃO

SELECT FIRST_NAME || ' ' || LAST_NAME || ', DATA DE ADMISSÃO: ' || HIRE_DATE "Funcionario"
FROM EMPLOYEES;

SELECT FIRST_NAME || ' ' || LAST_NAME || ', SALÁRIO: ' || SALARY "Funcionario"
FROM EMPLOYEES;

-- OPERADOR PARA ASPAS

SELECT DEPARTMENT_NAME || q'[ DEPARTMENT'S MANAGER ID: ]' || MANAGER_ID "Departamento e Gerente"
FROM DEPARTMENTS;

-- ELIMINANDO LINHAS DUPLICADAS

SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;


