-- UTILIZANDO WHERE

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE LAST_NAME = 'King';

SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE = '30/01/04';

-- OPERADORES DE COMPARAÇÃO

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= 10000;

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 15000;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, MANAGER_ID, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG', 'FI_ACCOUNT', 'SA_REP');

SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'Sa%';

SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_a%';

SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a';

-- COMPARAÇÃO COM NULL

SELECT LAST_NAME, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

-- OPERADORES LOGICOS AND, OR, NOT

SELECT employee_id, LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE SALARY >= 5000
AND JOB_ID = 'IT_PROG';

SELECT employee_id, LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE SALARY >= 5000
OR JOB_ID = 'IT_PROG';

SELECT employee_id, LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID NOT IN ('IT_PROG', 'FI ACCOUNT', 'SA_REP');

-- REGRAS DE PRECEDÊNCIA 

SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE (JOB_ID = 'SA_REP' OR JOB_ID = 'IT_PROG') AND SALARY > 10000;

-- ORDENANDO RESULTADOS ORDER BY

SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE ASC;

SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY*12 SALARIO_ANUAL
FROM EMPLOYEES
ORDER BY SALARIO_ANUAL;

SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY 4;

SELECT LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID, SALARY DESC;

-- VARIÁVEIS DE SUBSTITUIÇÃO

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EMPLOYEE_ID;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &&EMPLOYEE_ID;

-- VARIÁVEIS DE SUBSTITUIÇÃO CHARACTER E DATE

SELECT LAST_NAME, DEPARTMENT_ID, JOB_ID, SALARY*12
FROM EMPLOYEES
WHERE JOB_ID = '&JOB_ID';

-- DEFINE

DEFINE EMPLOYEE_ID = 101

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EMPLOYEE_ID;

DEFINE EMPLOYEE_ID

UNDEFINE EMPLOYEE_ID


